const fs = require('fs');

const heroArtworks = [
  {
    id: "luffy-one-piece",
    title: "Monkey D. Luffy",
    category: "Pop Culture",
    canvasShape: "rectangle",
    sizeDimensions: "4 x 6 inch Mini Canvas",
    medium: "Hand-Painted Acrylic on Woven Canvas",
    year: "2026",
    price: 200,
    inStock: true,
    description: "Hand-painted acrylic portrait of Luffy smiling in his straw hat against a vibrant ultramarine blue background. Styled alongside paint bottles & detail brush.",
    image: "/artworks/luffy.jpg",
    depthMap: "/artworks/cyber_samurai_depth.svg",
    colorPalette: ["#0044cc", "#ffaa00", "#cc0000", "#ffffff"],
    story: "Painted on a bright morning using rich ultramarine and vermilion acrylic pigments.",
    featured: true,
  },
  {
    id: "raincoat-duo",
    title: "Raincoat Duo (Stranger Things)",
    category: "Pop Culture",
    canvasShape: "heart",
    sizeDimensions: "5 x 5 inch Heart Canvas",
    medium: "Acrylic on Custom Heart Canvas",
    year: "2026",
    price: 200,
    inStock: true,
    description: "Handmade heart-shaped mini acrylic canvas depicting Eleven & Mike in red & yellow raincoats under blue rain, painted on deep forest green canvas.",
    image: "/artworks/raincoat_duo.jpg",
    depthMap: "/artworks/crystal_forest_depth.svg",
    colorPalette: ["#005533", "#cc0000", "#ffcc00", "#0044aa"],
    story: "Custom heart canvas cut & stretched to capture the warm bond between Mike & Eleven.",
    featured: true,
  },
  {
    id: "demogorgon-round",
    title: "Demogorgon Bloom",
    category: "Pop Culture",
    canvasShape: "circle",
    sizeDimensions: "4.5 inch Round Circular Canvas",
    medium: "Acrylic on Circular Canvas Board",
    year: "2026",
    price: 200,
    inStock: true,
    description: "Striking hand-painted circular mini canvas featuring the open flower-petal head of the Stranger Things Demogorgon with crimson teeth motifs.",
    image: "/artworks/demogorgon.jpg",
    depthMap: "/artworks/cyber_samurai_depth.svg",
    colorPalette: ["#0066aa", "#cc0022", "#331122", "#ffffff"],
    story: "Turning Hawkins monster lore into a handcrafted round desk display.",
    featured: true,
  },
  {
    id: "lightning-mcqueen",
    title: "Lightning McQueen 95",
    category: "Pop Culture",
    canvasShape: "square",
    sizeDimensions: "4 x 4 inch Mini Canvas",
    medium: "Vibrant Gloss Acrylic",
    year: "2026",
    price: 200,
    inStock: true,
    description: "Hand-painted mini square canvas featuring Pixar's Lightning McQueen with his yellow lightning bolt decal against a sky blue backdrop.",
    image: "/artworks/lightning_mcqueen.jpg",
    depthMap: "/artworks/neon_metropolis_depth.svg",
    colorPalette: ["#0066ff", "#dd0000", "#ffcc00", "#ffffff"],
    story: "Ka-Chow! Pure childhood nostalgia painted outdoors under the open sky.",
    featured: true,
  },
  {
    id: "batman-emblem",
    title: "The Dark Knight Emblem",
    category: "Pop Culture",
    canvasShape: "diamond",
    sizeDimensions: "4 x 4 inch Diamond Canvas",
    medium: "Matte Acrylic on Diamond Board",
    year: "2026",
    price: 200,
    inStock: true,
    description: "Classic yellow and matte black Batman logo emblem hand-painted on a diamond-oriented mini canvas frame.",
    image: "/artworks/batman.jpg",
    depthMap: "/artworks/neon_metropolis_depth.svg",
    colorPalette: ["#ffcc00", "#111116", "#ffffff", "#333333"],
    story: "The diamond canvas orientation adds dynamic architectural angles to Gotham's iconic silhouette.",
    featured: true,
  },
  {
    id: "pichwai-elephant",
    title: "Pichwai Blue Elephant",
    category: "Traditional",
    canvasShape: "rectangle",
    sizeDimensions: "5 x 4 inch Mini Canvas",
    medium: "Handcrafted Acrylic & Gold Detailing",
    year: "2026",
    price: 200,
    inStock: true,
    description: "Traditional Indian Pichwai-style blue elephant adorned with gold lotus patterns on a bright yellow acrylic canvas, held amidst lush green foliage.",
    image: "/artworks/pichwai_elephant.jpg",
    depthMap: "/artworks/cosmic_goddess_depth.svg",
    colorPalette: ["#ffcc00", "#0088ff", "#ffd700", "#006633"],
    story: "Inspired by the sacred temple arts of Rajasthan. Every gold motif is painted with a single-hair detail brush.",
    featured: true,
  },
  {
    id: "love-yourself-disco",
    title: "Love Yourself Groovy Disco",
    category: "Typography",
    canvasShape: "rectangle",
    sizeDimensions: "6 x 4 inch Mini Canvas",
    medium: "70s Retro Acrylic & Rhinestone Disc",
    year: "2026",
    price: 200,
    inStock: true,
    description: "Vibrant retro 70s groovy disco typography painted with warm red on lavender acrylic, featuring a glittering center disco ball & paint bottles.",
    image: "/artworks/love_yourself.jpg",
    depthMap: "/artworks/cosmic_goddess_depth.svg",
    colorPalette: ["#aa88ff", "#ee0044", "#ffcc00", "#ffffff"],
    story: "A daily reminder painted to slow down and appreciate oneself.",
    featured: true,
  },
  {
    id: "red-floral-study",
    title: "Vibrant Red Florals",
    category: "Landscapes & Illustrative",
    canvasShape: "rectangle",
    sizeDimensions: "5 x 3.5 inch Mini Canvas",
    medium: "Acrylic on Woven Canvas",
    year: "2026",
    price: 200,
    inStock: true,
    description: "Hand-painted vibrant red poppies on a bright marigold orange canvas board, featuring intricate stippled flower centers.",
    image: "/artworks/red_floral.jpg",
    depthMap: "/artworks/crystal_forest_depth.svg",
    colorPalette: ["#ffaa00", "#ee0000", "#332211", "#ffffff"],
    story: "Inspired by sunny garden blooms and bold graphic botanical shapes.",
    featured: true,
  },
  {
    id: "vaporwave-sunset-palms",
    title: "Vaporwave Twilight Palms",
    category: "Landscapes & Illustrative",
    canvasShape: "square",
    sizeDimensions: "4 x 4 inch Mini Canvas",
    medium: "Gradient Acrylic Blend",
    year: "2026",
    price: 200,
    inStock: true,
    description: "Retro synthwave sunset landscape with silhouette palm trees, streetlights, and crescent moon over a purple & pink cloud twilight.",
    image: "/artworks/vaporwave_sunset.jpg",
    depthMap: "/artworks/neon_metropolis_depth.svg",
    colorPalette: ["#8844cc", "#ff3366", "#ffcc00", "#111122"],
    story: "Smooth gradient blending created using soft fan brushes and twilight pigments.",
    featured: true,
  },
  {
    id: "kawaii-avocado",
    title: "Kawaii Mini Avocado",
    category: "Landscapes & Illustrative",
    canvasShape: "square",
    sizeDimensions: "3.5 x 3.5 inch Pink Mini Canvas",
    medium: "Matte Acrylic on Pink Canvas",
    year: "2025",
    price: 200,
    inStock: true,
    description: "Cute smiling kawaii avocado slice hand-painted on a vibrant hot pink mini square canvas, photographed amidst garden flora.",
    image: "/artworks/kawaii_avocado.jpg",
    depthMap: "/artworks/crystal_forest_depth.svg",
    colorPalette: ["#ff0066", "#33cc33", "#663300", "#ffffff"],
    story: "One of the favorite mini pieces that brings an instant smile to everyone who sees it!",
    featured: true,
  },
];

const batch1 = [
  { id: "art_01", title: "Sunset Cloudscape & Tree Silhouettes", category: "Landscapes & Illustrative", canvasShape: "rectangle", sizeDimensions: "4 x 6 inch Mini Canvas", description: "A vibrant sunset acrylic landscape featuring layered cloud formations and tree silhouettes alongside paint bottles." },
  { id: "art_02", title: "Starry Night Lightbulb", category: "Pop Culture", canvasShape: "circle", sizeDimensions: "4.5 inch Round Canvas", description: "A hand-painted lightbulb featuring Van Gogh's iconic Starry Night swirling pattern held against a pink flower garden." },
  { id: "art_03", title: "Red Starfish in Ocean", category: "Landscapes & Illustrative", canvasShape: "rectangle", sizeDimensions: "4 x 6 inch Mini Canvas", description: "An illustrative red starfish surrounded by white bubbles painted on a teal blue sketchbook page." },
  { id: "art_04", title: "Spider-Man Diamond Portrait", category: "Pop Culture", canvasShape: "diamond", sizeDimensions: "4 x 4 inch Diamond Canvas", description: "A classic Spider-Man bust portrait framed within a bold diamond outline on a sketchbook page." },
  { id: "art_05", title: "Crescent Moon Camping Landscape", category: "Landscapes & Illustrative", canvasShape: "rectangle", sizeDimensions: "4 x 6 inch Mini Canvas", description: "A detailed ink stippling illustration of a cozy camping tent and starry sky framed inside a crescent moon." },
  { id: "art_06", title: "Hobbit Hole Blue Door", category: "Pop Culture", canvasShape: "circle", sizeDimensions: "4.5 inch Round Canvas", description: "A charming Lord of the Rings inspired circular blue Hobbit door surrounded by stonework and purple flowers." },
  { id: "art_07", title: "Ocean Seashell Mini Canvas", category: "Landscapes & Illustrative", canvasShape: "rectangle", sizeDimensions: "5 x 4 inch Mini Canvas", description: "A small turquoise canvas layered with real seashells, artfully displayed in the center of a circular shell arrangement." },
  { id: "art_08", title: "Twin Red Tulips", category: "Landscapes & Illustrative", canvasShape: "rectangle", sizeDimensions: "4 x 6 inch Mini Canvas", description: "Two vibrant red tulips with bold black outlines painted against a textured deep blue acrylic backdrop." },
  { id: "art_09", title: "Stitch Holding Red Heart", category: "Pop Culture", canvasShape: "heart", sizeDimensions: "5 x 5 inch Heart Canvas", description: "A cute hand-painted illustration of Stitch from Lilo & Stitch lovingly hugging a big red heart on a red background." },
  { id: "art_10", title: "Spider-Man Symbol", category: "Pop Culture", canvasShape: "rectangle", sizeDimensions: "4 x 6 inch Mini Canvas", description: "The iconic black Spider-Man spider emblem painted centered on a vibrant red paper canvas." },
  { id: "art_11", title: "Spider-Man vs Venom Split Face", category: "Pop Culture", canvasShape: "square", sizeDimensions: "4 x 4 inch Square Canvas", description: "A dramatic half-Spider-Man half-Venom split mask illustration with a long pink tongue on a dark blue square backdrop." },
  { id: "art_12", title: "Three Red Tulips", category: "Landscapes & Illustrative", canvasShape: "rectangle", sizeDimensions: "4 x 6 inch Mini Canvas", description: "A clean botanical painting of three bright red tulips with green leaves on a vibrant turquoise canvas." },
  { id: "art_13", title: "Iron Man Helmet Mask", category: "Pop Culture", canvasShape: "rectangle", sizeDimensions: "4 x 6 inch Mini Canvas", description: "A classic red and yellow Iron Man helmet mask painted against a rich blue rectangular mini canvas." },
  { id: "art_14", title: "Twilight Palm Sunset", category: "Landscapes & Illustrative", canvasShape: "square", sizeDimensions: "4 x 4 inch Square Canvas", description: "A retro purple and pink sunset scene with palm tree silhouettes and street lamps painted on a mini square canvas." },
  { id: "art_15", title: "Textured Letter 'G' with Hearts", category: "Typography", canvasShape: "rectangle", sizeDimensions: "5 x 4 inch Mini Canvas", description: "A tactile pink mini canvas showcasing a fluffy red tufted letter 'G' accented with mini red heart shapes." },
  { id: "art_16", title: "Retro Red Poppy Pattern", category: "Landscapes & Illustrative", canvasShape: "rectangle", sizeDimensions: "5 x 4 inch Mini Canvas", description: "A bold 70s style botanical pattern featuring stylized red poppies with dotted centers on a bright orange canvas." },
  { id: "art_17", title: "Red Hearts on Vintage Book Page", category: "Typography", canvasShape: "heart", sizeDimensions: "5 x 4 inch Mini Canvas", description: "A vintage torn book page adorned with layered red paper heart cutouts creating a romantic collage." },
  { id: "art_18", title: "Surreal Anatomical Studies on Vintage Paper", category: "Landscapes & Illustrative", canvasShape: "rectangle", sizeDimensions: "5 x 4 inch Mini Canvas", description: "A trio of burnt-edge antique book paper scraps featuring red ink illustrations of a skeleton hand, surreal eyes, and an anatomical heart." },
  { id: "art_19", title: "Anatomical Heart on Vintage Page", category: "Landscapes & Illustrative", canvasShape: "heart", sizeDimensions: "5 x 5 inch Heart Canvas", description: "A detailed red anatomical heart illustration painted over a rustic burnt-edge vintage book page." },
  { id: "art_20", title: "Insaan Hindi Typography", category: "Typography", canvasShape: "rectangle", sizeDimensions: "6 x 4 inch Mini Canvas", description: "Bold yellow Hindi Devanagari typography spelling 'इंसान' (Insaan) on a warm rust orange background." },
  { id: "art_21", title: "Helna Hindi Typography", category: "Typography", canvasShape: "rectangle", sizeDimensions: "6 x 4 inch Mini Canvas", description: "Vibrant yellow graphic Hindi Devanagari typography reading 'हेलना' painted against a deep forest green backdrop." },
  { id: "art_22", title: "Spider-Man Electric Aura", category: "Pop Culture", canvasShape: "rectangle", sizeDimensions: "4 x 6 inch Mini Canvas", description: "A hand-painted mini card featuring Spider-Man surrounded by yellow lightning bolts and blue textured brushstrokes." },
  { id: "art_23", title: "The Dark Knight Bat Emblem", category: "Pop Culture", canvasShape: "diamond", sizeDimensions: "4 x 4 inch Diamond Canvas", description: "The classic yellow Batman insignia painted on a black canvas displayed in a diamond orientation." },
  { id: "art_24", title: "Spider-Man & Spider-Gwen Pixel Hearts", category: "Pop Culture", canvasShape: "heart", sizeDimensions: "5 x 5 inch Heart Canvas", description: "Two handcrafted pixel art heart cutouts themed after Spider-Man and Spider-Gwen." },
  { id: "art_25", title: "STAR Graphic Star Canvas", category: "Typography", canvasShape: "diamond", sizeDimensions: "4 x 4 inch Diamond Canvas", description: "A star-shaped cut canvas painted yellow with red borders containing bold 'STAR' typography." },
  { id: "art_26", title: "Love Yourself Groovy Disco", category: "Typography", canvasShape: "rectangle", sizeDimensions: "6 x 4 inch Mini Canvas", description: "Retro 70s groovy typography spelling 'LOVE YOURSELF' on lavender canvas with a glittering disco ball and sparkle accents." },
  { id: "art_27", title: "Kawaii Tomatoes in Yellow Bag", category: "Landscapes & Illustrative", canvasShape: "rectangle", sizeDimensions: "5 x 4 inch Mini Canvas", description: "A cute illustration of smiling kawaii red tomatoes peeking out of a yellow bag painted on a sketchbook page in front of pink blossoms." },
  { id: "art_28", title: "Wildflower Garden Sketch", category: "Landscapes & Illustrative", canvasShape: "rectangle", sizeDimensions: "5 x 4 inch Mini Canvas", description: "A lively arrangement of colorful hand-painted wildflowers on a pastel peach background inside an open sketchbook." },
  { id: "art_29", title: "Cute Cartoon Cow", category: "Landscapes & Illustrative", canvasShape: "rectangle", sizeDimensions: "5 x 4 inch Mini Canvas", description: "A quirky cartoon cow illustration with wide eyes against a bold red background painted on a sketchbook page outdoors." },
  { id: "art_30", title: "Apple Hat Kawaii Cat", category: "Landscapes & Illustrative", canvasShape: "rectangle", sizeDimensions: "5 x 4 inch Mini Canvas", description: "A whimsical kawaii white cat character wearing a bright red apple hood painted on a vibrant green sketchbook page." }
];

const batch2 = [
  { id: "art_31", title: "Star Hat Blue Cat", category: "Landscapes & Illustrative", canvasShape: "rectangle", sizeDimensions: "4 x 6 inch Mini Canvas", description: "Hand-painted blue cat wearing a bright yellow star headpiece with spiral antennae on a dark purple background inside a sketchbook." },
  { id: "art_32", title: "Pichwai Royal Elephant", category: "Traditional", canvasShape: "rectangle", sizeDimensions: "5 x 4 inch Mini Canvas", description: "Traditional Indian Pichwai-style blue elephant adorned with gold and pink lotus motifs on a bright yellow canvas." },
  { id: "art_33", title: "Miffy the Bunny", category: "Pop Culture", canvasShape: "rectangle", sizeDimensions: "4 x 6 inch Mini Canvas", description: "Cute hand-painted illustration of Miffy the bunny in a red collar against a teal outline and lime yellow starry background." },
  { id: "art_34", title: "Pichwai Blue Elephant", category: "Traditional", canvasShape: "rectangle", sizeDimensions: "5 x 4 inch Mini Canvas", description: "Traditional Pichwai artwork of a decorated blue elephant surrounded by lotus blossoms painted on a yellow canvas." },
  { id: "art_35", title: "Spider-Man Mask & Emblem", category: "Pop Culture", canvasShape: "rectangle", sizeDimensions: "4 x 6 inch Mini Canvas", description: "Pair of hand-painted black rectangular canvases featuring Spider-Man's masked face and iconic red spider emblem." },
  { id: "art_36", title: "Spider-Man Heart & Lightning", category: "Pop Culture", canvasShape: "rectangle", sizeDimensions: "4 x 6 inch Mini Canvas", description: "Hand-painted heart-shaped Spider-Man mask with yellow lightning bolts on a dark blue background card." },
  { id: "art_37", title: "Heart Spiderweb", category: "Pop Culture", canvasShape: "rectangle", sizeDimensions: "4 x 6 inch Mini Canvas", description: "Minimalist white line art painting of a heart-shaped spiderweb on a crimson red background card." },
  { id: "art_38", title: "Mushroom Frog", category: "Landscapes & Illustrative", canvasShape: "rectangle", sizeDimensions: "4 x 6 inch Mini Canvas", description: "Cute hand-painted green frog wearing a red mushroom cap with yellow spots against a lavender purple backdrop." },
  { id: "art_39", title: "Monkey D. Luffy", category: "Pop Culture", canvasShape: "rectangle", sizeDimensions: "4 x 6 inch Mini Canvas", description: "Hand-painted acrylic portrait of Luffy smiling in his straw hat against a vibrant ultramarine blue background." },
  { id: "art_40", title: "Pixel Art F1 Race Car", category: "Pop Culture", canvasShape: "rectangle", sizeDimensions: "4 x 6 inch Mini Canvas", description: "Pixel art cut-out of a red and black Formula 1 racing car with yellow accents, painted in a retro grid style." },
  { id: "art_41", title: "BMW M Motorsport Pixel Logo", category: "Pop Culture", canvasShape: "rectangle", sizeDimensions: "6 x 3 inch Mini Canvas", description: "Pixel art cut-out canvas depicting the iconic BMW M Motorsport logo in light blue, dark blue, and red stripes." },
  { id: "art_42", title: "Lightning McQueen 95", category: "Pop Culture", canvasShape: "square", sizeDimensions: "4 x 4 inch Square Canvas", description: "Hand-painted mini square canvas featuring Pixar's Lightning McQueen with his yellow lightning bolt decal against a bright blue sky backdrop." },
  { id: "art_43", title: "Lavender Field Keychain", category: "Landscapes & Illustrative", canvasShape: "square", sizeDimensions: "2 x 2 inch Square Canvas", description: "Hand-painted mini square canvas keychain featuring vibrant purple lavender blooms over green grass on a black background." },
  { id: "art_44", title: "Hanging Floral Vines", category: "Landscapes & Illustrative", canvasShape: "rectangle", sizeDimensions: "4 x 6 inch Mini Canvas", description: "Hand-painted green vines with delicate pink flower buds cascading down a soft green background in a sketchbook." },
  { id: "art_45", title: "Pixel Art Green Frog", category: "Pop Culture", canvasShape: "square", sizeDimensions: "4 x 4 inch Square Canvas", description: "Charming pixelated green frog face cut-out with pink cheeks painted on grid square canvas." },
  { id: "art_46", title: "Watermelon Slice Pattern", category: "Landscapes & Illustrative", canvasShape: "rectangle", sizeDimensions: "4 x 6 inch Mini Canvas", description: "Bright yellow sketchbook page decorated with bold red and green watermelon slices and black seed details." },
  { id: "art_47", title: "Cosmic Manta Ray", category: "Landscapes & Illustrative", canvasShape: "rectangle", sizeDimensions: "4 x 6 inch Mini Canvas", description: "Deep blue star-spotted manta ray swimming in bright cyan ocean waters painted inside a sketchbook." },
  { id: "art_48", title: "Groovy Vinyl Heart", category: "Pop Culture", canvasShape: "rectangle", sizeDimensions: "4 x 6 inch Mini Canvas", description: "Black vinyl record motif in a heart shape with a red center against wavy pink liquid background patterns." },
  { id: "art_49", title: "Demogorgon Bloom", category: "Pop Culture", canvasShape: "circle", sizeDimensions: "4.5 inch Round Circular Canvas", description: "Striking hand-painted circular mini canvas featuring the open flower-petal head of the Stranger Things Demogorgon." },
  { id: "art_50", title: "Starry Night Floral Wood Slice", category: "Landscapes & Illustrative", canvasShape: "circle", sizeDimensions: "4 inch Round Canvas", description: "Hand-painted circular wooden slice depicting a crescent moon in a starry night sky above red flower bushes." },
  { id: "art_51", title: "Kawaii Mini Avocado", category: "Landscapes & Illustrative", canvasShape: "square", sizeDimensions: "3.5 x 3.5 inch Square Canvas", description: "Cute smiling kawaii avocado slice hand-painted on a vibrant hot pink mini square canvas." },
  { id: "art_52", title: "Moonlit Mountain Peaks", category: "Landscapes & Illustrative", canvasShape: "square", sizeDimensions: "4 x 4 inch Square Canvas", description: "Silhouetted black mountain peaks under a glowing full moon and starry cobalt blue gradient night sky." },
  { id: "art_53", title: "Spider-Man Custom Phone Case", category: "Pop Culture", canvasShape: "rectangle", sizeDimensions: "4 x 6 inch Mini Canvas", description: "Hand-painted smartphone protective case featuring Spider-Man's red mask web design and expressive eyes." },
  { id: "art_54", title: "Twin Koi Fish Pond", category: "Landscapes & Illustrative", canvasShape: "rectangle", sizeDimensions: "4 x 6 inch Mini Canvas", description: "Hand-painted orange and red Koi fish swimming gracefully around green lily pads in clear turquoise water." },
  { id: "art_55", title: "Moonlight Dandelions", category: "Landscapes & Illustrative", canvasShape: "circle", sizeDimensions: "4.5 inch Round Circular Canvas", description: "Monochromatic circular canvas painting showing white dandelion seed clusters floating against a dark lunar sky." },
  { id: "art_56", title: "Classic Red Rose", category: "Landscapes & Illustrative", canvasShape: "rectangle", sizeDimensions: "4 x 6 inch Mini Canvas", description: "Hand-painted red rose on a leafy green stem set against a bright yellow background card." },
  { id: "art_57", title: "Coastal Lighthouse", category: "Landscapes & Illustrative", canvasShape: "rectangle", sizeDimensions: "4 x 6 inch Mini Canvas", description: "Red and white striped lighthouse perched on rocky ground under a bright blue sky filled with fluffy white clouds." },
  { id: "art_58", title: "Spider-Gwen (Ghost-Spider)", category: "Pop Culture", canvasShape: "rectangle", sizeDimensions: "4 x 6 inch Mini Canvas", description: "Hand-painted acrylic portrait of Spider-Gwen in her white hooded costume against a vibrant blue backdrop." },
  { id: "art_59", title: "The Starry Night (Van Gogh Tribute)", category: "Traditional", canvasShape: "rectangle", sizeDimensions: "5 x 4 inch Mini Canvas", description: "Vibrant hand-painted tribute to Vincent van Gogh's 'The Starry Night' on canvas." },
  { id: "art_60", title: "Whale Shark in Ocean Ripples", category: "Landscapes & Illustrative", canvasShape: "rectangle", sizeDimensions: "4 x 6 inch Mini Canvas", description: "Dotted whale shark gliding through turquoise water with white sunlit wave patterns in a sketchbook." }
];

const batch3 = [
  { id: "art_61", title: "Shin-chan", category: "Pop Culture", canvasShape: "rectangle", sizeDimensions: "4 x 6 inch Mini Canvas", description: "Hand-painted acrylic illustration of Shin-chan waving his hand against a bright cyan blue background." },
  { id: "art_62", title: "Cute White Duck", category: "Landscapes & Illustrative", canvasShape: "square", sizeDimensions: "4 x 4 inch Square Canvas", description: "Charming mini square canvas painting of a cute white duck with an orange beak on a vibrant sky blue background." },
  { id: "art_63", title: "Pink Lily Bloom", category: "Landscapes & Illustrative", canvasShape: "rectangle", sizeDimensions: "5 x 4 inch Mini Canvas", description: "Vibrant acrylic floral painting of a blooming pink lily with green leaves on a bright marigold yellow background." },
  { id: "art_64", title: "Textured Red Hearts Pattern", category: "Landscapes & Illustrative", canvasShape: "rectangle", sizeDimensions: "5 x 4 inch Mini Canvas", description: "Vertical white canvas featuring six raised textured red heart paint motifs arranged across the surface." },
  { id: "art_65", title: "Midnight Red Roses", category: "Landscapes & Illustrative", canvasShape: "rectangle", sizeDimensions: "4 x 6 inch Mini Canvas", description: "Polaroid-style artwork depicting hand-painted red roses and green leaves scattered across a textured dark background." },
  { id: "art_66", title: "Warli Tribal Dancer", category: "Traditional", canvasShape: "rectangle", sizeDimensions: "5 x 4 inch Mini Canvas", description: "Traditional Indian Warli tribal dance figure painted in red and yellow accents on an olive green textured background." },
  { id: "art_67", title: "Batman & Hello Kitty Duo", category: "Pop Culture", canvasShape: "rectangle", sizeDimensions: "6 x 4 inch Mini Canvas", description: "Charming pop culture acrylic artwork depicting chibi Batman and Hello Kitty side by side on a bold red background." },
  { id: "art_68", title: "Blooming Orange Tulips", category: "Landscapes & Illustrative", canvasShape: "rectangle", sizeDimensions: "4 x 6 inch Mini Canvas", description: "Hand-painted polaroid-style artwork of bright orange tulips with green leaves on a soft pink background." },
  { id: "art_69", title: "Moonlit Mountain Landscape", category: "Landscapes & Illustrative", canvasShape: "square", sizeDimensions: "4 x 4 inch Square Canvas", description: "Serene night landscape featuring a bright golden full moon and starry blue gradient sky over dark mountain silhouettes." },
  { id: "art_70", title: "Green Organic Abstract", category: "Landscapes & Illustrative", canvasShape: "rectangle", sizeDimensions: "4 x 6 inch Mini Canvas", description: "Abstract Polaroid artwork featuring flowing green and teal organic shapes with white line work and dot accents." },
  { id: "art_71", title: "Spider-Man Heart Mask", category: "Pop Culture", canvasShape: "rectangle", sizeDimensions: "4 x 6 inch Mini Canvas", description: "Polaroid-style acrylic painting featuring a heart-shaped Spider-Man mask motif on a bright yellow background." },
  { id: "art_72", title: "Anya Forger (Spy x Family)", category: "Pop Culture", canvasShape: "rectangle", sizeDimensions: "5 x 4 inch Mini Canvas", description: "Hand-painted anime portrait of Anya Forger with wide green eyes and spiky pink hair on a purple canvas." },
  { id: "art_73", title: "Girl with Red Hair Bow", category: "Landscapes & Illustrative", canvasShape: "rectangle", sizeDimensions: "5 x 4 inch Mini Canvas", description: "Illustrative painting of a girl with long wavy hair tied with a red ribbon bow, surrounded by a pink painted cloud border." },
  { id: "art_74", title: "Lime Green Duckling", category: "Landscapes & Illustrative", canvasShape: "rectangle", sizeDimensions: "4 x 6 inch Mini Canvas", description: "Minimalist polaroid-style artwork depicting a white duck outline with an orange beak on a vivid lime green background." },
  { id: "art_75", title: "High Five Paw & Hand", category: "Landscapes & Illustrative", canvasShape: "rectangle", sizeDimensions: "4 x 6 inch Mini Canvas", description: "Heartwarming illustration of a human hand giving a high-five to a cat paw against a warm peach background." },
  { id: "art_76", title: "Pink Bows & Hearts Pattern", category: "Landscapes & Illustrative", canvasShape: "rectangle", sizeDimensions: "4 x 6 inch Mini Canvas", description: "Delicate polaroid-style painting featuring a repeating pattern of pink ribbon bows and white hearts on a pink background." },
  { id: "art_77", title: "Heart Flower Stems", category: "Landscapes & Illustrative", canvasShape: "rectangle", sizeDimensions: "4 x 6 inch Mini Canvas", description: "Cute polaroid artwork of red heart-shaped flower buds growing on green vines against a speckled yellow background." },
  { id: "art_78", title: "Trio of Red Tulips", category: "Landscapes & Illustrative", canvasShape: "rectangle", sizeDimensions: "4 x 6 inch Mini Canvas", description: "Vibrant polaroid painting featuring three bold red tulips with clean black outlines on a yellow background." },
  { id: "art_79", title: "Anatomical Heart on Pastel Camo", category: "Landscapes & Illustrative", canvasShape: "heart", sizeDimensions: "5 x 5 inch Heart Canvas", description: "Heart-shaped acrylic canvas showcasing a detailed crimson anatomical heart against a pastel camouflage background." },
  { id: "art_80", title: "Twilight Street Lamps", category: "Landscapes & Illustrative", canvasShape: "rectangle", sizeDimensions: "6 x 4 inch Mini Canvas", description: "Serene twilight scenery painting showing glowing streetlamps and tree silhouettes under a soft pastel lavender and pink sky." },
  { id: "art_81", title: "Super Mario Mushrooms Duo", category: "Pop Culture", canvasShape: "rectangle", sizeDimensions: "4 x 6 inch Mini Canvas", description: "Pop culture painting pair featuring the iconic red Super Mushroom and green 1-Up Mushroom from Super Mario." },
  { id: "art_82", title: "Purple Butterfly on Crimson", category: "Landscapes & Illustrative", canvasShape: "circle", sizeDimensions: "4.5 inch Round Circular Canvas", description: "Vibrant round circular canvas featuring a hand-painted deep purple butterfly on a bold crimson red backdrop." },
  { id: "art_83", title: "Doraemon", category: "Pop Culture", canvasShape: "circle", sizeDimensions: "4.5 inch Round Circular Canvas", description: "Cheerful round mini canvas painting of the classic anime character Doraemon on a warm orange background." },
  { id: "art_84", title: "Single Red Rose", category: "Landscapes & Illustrative", canvasShape: "square", sizeDimensions: "4 x 4 inch Square Canvas", description: "Elegant square mini canvas featuring a single detailed red rose with crisp black outlines on a terracotta red background." },
  { id: "art_85", title: "Besties Forever Pinky Promise", category: "Typography", canvasShape: "square", sizeDimensions: "4 x 4 inch Square Canvas", description: "Hand-painted square canvas depicting a pinky promise illustration with 'besties FOREVER' typography over a galaxy sky background." },
  { id: "art_86", title: "Bikini Bottom Porthole", category: "Pop Culture", canvasShape: "circle", sizeDimensions: "4.5 inch Round Circular Canvas", description: "Circular canvas painted like a submarine porthole looking out into the underwater landscape of SpongeBob's Bikini Bottom." },
  { id: "art_87", title: "Shin-chan Flexing", category: "Pop Culture", canvasShape: "square", sizeDimensions: "4 x 4 inch Square Canvas", description: "Hand-painted square mini canvas showing Shin-chan flexing his arm in his signature pajamas on a bold red background." },
  { id: "art_88", title: "Raincoat Duo on Emerald Heart", category: "Pop Culture", canvasShape: "heart", sizeDimensions: "5 x 5 inch Heart Canvas", description: "Heart-shaped acrylic canvas painted with two minimalist figures wearing bright red and yellow raincoats on a deep emerald green background." },
  { id: "art_89", title: "Taiju Shiba (Tokyo Revengers)", category: "Pop Culture", canvasShape: "rectangle", sizeDimensions: "5 x 4 inch Mini Canvas", description: "Anime portrait canvas of Taiju Shiba from Tokyo Revengers wearing his signature red Black Dragon coat on a navy blue background." },
  { id: "art_90", title: "Duo in Suits on Purple Heart", category: "Pop Culture", canvasShape: "heart", sizeDimensions: "5 x 5 inch Heart Canvas", description: "Heart-shaped purple acrylic canvas depicting two stylized figures in dark suits sharing a moment together." },
  { id: "art_91", title: "Low-Poly Geometric Heart", category: "Landscapes & Illustrative", canvasShape: "rectangle", sizeDimensions: "5 x 4 inch Mini Canvas", description: "Low-poly geometric artwork of a human heart rendered in facets of ruby red on a cream background." },
  { id: "art_92", title: "Under the Sea Porthole View", category: "Pop Culture", canvasShape: "circle", sizeDimensions: "4.5 inch Round Circular Canvas", description: "Round circular canvas showcasing SpongeBob's underwater sky flowers and coral reef scene viewed through a blue porthole." },
  { id: "art_93", title: "Starry Night Study", category: "Traditional", canvasShape: "rectangle", sizeDimensions: "6 x 4 inch Mini Canvas", description: "Hand-painted acrylic tribute to Van Gogh's 'The Starry Night' featuring swirling golden stars and blue nocturnal sky." },
  { id: "art_94", title: "Ryomen Sukuna (Jujutsu Kaisen)", category: "Pop Culture", canvasShape: "rectangle", sizeDimensions: "5 x 4 inch Mini Canvas", description: "Bold acrylic anime portrait of Sukuna from Jujutsu Kaisen with spiky pink hair and black facial markings on a dark teal background." },
  { id: "art_95", title: "Shoyo Hinata (Haikyuu!!)", category: "Pop Culture", canvasShape: "square", sizeDimensions: "4 x 4 inch Square Canvas", description: "Vibrant mini square canvas portrait of Shoyo Hinata from Haikyuu!! smiling cheerfully against a rich dark green background." }
];

const allInspected = [...batch1, ...batch2, ...batch3];

const fullList = [...heroArtworks];

allInspected.forEach((item, index) => {
  const num = (index + 1).toString().padStart(2, '0');
  const imgName = `art_${num}.jpg`;

  fullList.push({
    id: `canvas-${num}`,
    title: item.title,
    category: item.category,
    canvasShape: item.canvasShape,
    sizeDimensions: item.sizeDimensions,
    medium: 'Hand-Painted Acrylic on Canvas',
    year: '2026',
    price: 200,
    inStock: true,
    description: item.description,
    image: `/artworks/collection/${imgName}`,
    depthMap: '/artworks/cyber_samurai_depth.svg',
    colorPalette: ['#e69c24', '#d97a5b', '#7a8b7b', '#ffffff'],
    story: `Handcrafted with care by Guna using rich acrylic pigments on canvas.`,
    featured: false,
  });
});

const tsContent = `export type CanvasShape = "rectangle" | "square" | "circle" | "heart" | "diamond";

export interface Artwork {
  id: string;
  title: string;
  category: "Pop Culture" | "Traditional" | "Typography" | "Landscapes & Illustrative";
  canvasShape: CanvasShape;
  sizeDimensions: string;
  medium: string;
  year: string;
  price: number; // Price in INR (₹)
  inStock: boolean;
  description: string;
  image: string;
  depthMap: string;
  colorPalette: string[];
  story: string;
  featured: boolean;
}

export const ARTWORKS: Artwork[] = ${JSON.stringify(fullList, null, 2)};
`;

fs.writeFileSync('c:/Users/Padmajaa/OneDrive/Desktop/portfolio artt/src/data/artworks.ts', tsContent);
console.log(`Successfully compiled artworks.ts dataset with ${fullList.length} uniquely titled & described items!`);
